openapi: 3.0.0
info:
  title: Health Service API
  version: 1.0.0
  description: 健康檢查 API 文件

servers:
  - url: http://172.21.122.231:8099/fb1cfee0/health

paths:
  /health:
    get:
      summary: health_check
      description: 取得健康檢查資訊
      tags:
        - health
      responses:
        '200':
          description: 成功取得健康檢查資訊
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
        message:
          type: string
          example: Service is healthy

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 1234
        message:
          type: string
          example: "Invalid request"
