version: 2
#certificate: # 证书存放根目录
#  dir: /etc/apinto/cert
client:
 advertise_urls: # open api 服务的广播地址
   - http://172.21.122.231:9400
 listen_urls: # open api 服务的监听地址
   - http://0.0.0.0:9400
 #certificate:  # 证书配置，允许使用ip的自签证书
 #  - cert: server.pem
 #    key: server.key
gateway:
 advertise_urls: # 转发服务的广播地址
   - http://114.33.48.242:8099
   - https://114.33.48.242:8099
   - http://172.21.122.231:8099
   - https://172.21.122.231:8099
 listen_urls: # 转发服务的监听地址
   - https://0.0.0.0:8099
   - http://0.0.0.0:8099
peer: # 集群间节点通信配置信息
 listen_urls: # 节点监听地址
   - http://0.0.0.0:9401
 advertise_urls: # 节点通信广播地址
   - http://172.21.122.231:9401
 #certificate:  # 证书配置，允许使用ip的自签证书
 #  - cert: server.pem
 #    key: server.key

